### ISSUE TITLE
Homepage search leads to a 404 page when EN is selected

### ISSUE THREAD

**Issue by naokomc** [Automattic/GlotPress-WP#1]
The "Search for text or translation" box on the front page of translate.wordpress.com lets you choose English as a locale. 

![image](https://user-images.githubusercontent.com/34067/37074608-fe8c67dc-2210-11e8-8809-27d5ecb2103a.png)

However, doing so takes you to the result page URL like this: https://translate.wordpress.com/projects/wpcom/en/default?filters%5Bterm%5D=site

It's a 404 page since we don't have <code>/en/</code> locale in GlotPress.
Could you remove English from the dropdown list?

**Comment by akirk** [comment]
I've removed English from the dropdown.
